title: SimpleID
description: 'SimpleID is a simple, personal OpenID provider written in PHP.'

sourceforge:
    project_url: http://sourceforge.net/projects/simpleid
    group_id: 203264

collections:
    docs:
        output: true
    api:
        output: true

permalink: /:categories/:year/:month/:title/

exclude: 
    - .rvmrc
    - .rbenv-version
    - CNAME
    - README.md
    - Gemfile
    - vendor

markdown: kramdown

highlighter: rouge

gems:
    - jekyll-redirect-from
